server:
  port: 8095
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_DATASOURCE_URL}
    username: ${MYSQL_DATASOURCE_USERNAME}
    password: ${MYSQL_DATASOURCE_PASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    show-sql: false
keycloak:
  custom:
    server:
      context-path: "/auth"

    infinispan:
      config-location: "classpath:infinispan-cluster.xml"

    adminUser:
      username: admin
      password: admin
    import-location: hello-spring-realm.json
    create-admin-user: false
    create-realm: false