server:
  port: 9090
  servlet:
    context-path: /gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    enabled: false
logging:
  level:
    org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: DEBUG
    org.springframework.web.reactive.function.client.ExchangeFunctions: DEBUG
cors:
  max-age: 3600
  allow-origins:
    - http://localhost:4200
  allowed-headers: "*"
  allowed-methods: "*"
  exposed-headers:
    - content-length
    - authorization
  apply-path: "/**"
spring:
  application:
    name: gateway-server
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8095/auth/realms/prm
          jwk-set-uri: http://localhost:8095/auth/realms/prm/protocol/openid-connect/certs
          jws-algorithm: RS256
  cloud:
    gateway:
      routes:
        - id: account_route
          uri: http://localhost:9091 #lb://ACCOUNT-SERVICE
          predicates:
            - Path=/gateway/account/**
          filters:
            - RewritePath=/gateway/account/(?<segment>.*), /account-service/api/$\{segment}