server:
  port: 9091
  servlet:
    context-path: /account-service
spring:
  application:
    name: account-service
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    show-sql: true
