server:
  port: 9091
  servlet:
    context-path: /account-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    enabled: false
spring:
  application:
    name: account-service
  h2:
    console:
      enabled: true
  mustache:
    enabled: false
    check-template-location: false
  datasource:
    # url: jdbc:h2:mem:testdb
    # username: sa
    # password:
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true
    show-sql: true
keycloak:
  server-url: ${KEYCLOAK_URL}
  realm: ${KEYCLOAK_REALM}
  username: ${KEYCLOAK_USERNAME}
  password: ${KEYCLOAK_PASSWORD}
  client-id: ${KEYCLOAK_CLIENT_ID}
  client-secret: ${KEYCLOAK_CLIENT_SECRET}
  id-web-spa: ${KEYCLOAK_ID_WEB_ADMIN}