openapi: 3.0.3
info:
  title: Account # dont change this line
  description: Account Api Docs
  version: 1.0.0
servers:
  - url: 'http://localhost:9091/account-service'
tags:
  - name: feature
    description: Feature Tag
paths:
  /api/feature/list:
    get:
      summary: return list feature
      description: return list feature
      operationId: getFeatures
      tags:
        - feature
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FeatureResponse'
          description: response Feature List
  /api/feature/menu:
    get:
      summary: return menu by user logged in
      description: return menu by user logged in
      operationId: getMenu
      tags:
        - feature
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MenuResponse'
          description: response Menu to user logged in
  /api/feature/menu-transformed:
    get:
      summary: return menu by user logged in
      description: return menu by user logged in
      operationId: getMenuTransformed
      tags:
        - feature
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MenuTransformedResponse'
          description: response Menu to user loggedIn and maintain structure
  /api/feature/page/{id}/{limit}:
    get:
      summary: return features with paging
      description: return features with paging
      operationId: getFeatureWithPage
      tags:
        - feature
      parameters:
        - in: path
          name: id
          schema:
            type: integer
            format: int64
          required: true
          description: id of last feature in list response
        - in: path
          name: limit
          schema:
            type: integer
          required: true
          description: limit item
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FeaturePageResponse'
          description: response Features and pagination
components:
  schemas:
    FeatureResponse:
      type: object
      title: FeatureResponse
      additionalProperties: false
      properties:
        result:
          $ref: 'lib/common.yaml#/components/schemas/ApiResult'
        context:
          type: array
          items:
            $ref: '#/components/schemas/FeatureDto'
    MenuResponse:
      type: object
      title: MenuResponse
      additionalProperties: false
      properties:
        result:
          $ref: 'lib/common.yaml#/components/schemas/ApiResult'
        context:
          type: array
          items:
            $ref: '#/components/schemas/FeatureGroupDto'
    MenuTransformedResponse:
      type: object
      title: MenuTransformedResponse
      additionalProperties: false
      properties:
        result:
          $ref: 'lib/common.yaml#/components/schemas/ApiResult'
        context:
          type: object
          additionalProperties: false
          properties:
            groups:
              type: array
              items:
                $ref: '#/components/schemas/GroupMenuFeatureDto'
            standalone:
              type: array
              items:
                $ref: '#/components/schemas/FeatureDto'
    FeatureGroupDto:
      type: object
      title: FeatureDto
      additionalProperties: false
      properties:
        id:
          type: integer
          format: int64
        label:
          type: string
        icon:
          type: string
        routerLink:
          type: string
        hasChildren:
          type: boolean
        parent:
          type: integer
          format: int64
        showInMenu:
          type: boolean
        orderValue:
          type: integer
        groupMenu:
          $ref: '#/components/schemas/GroupMenuDto'
    FeatureDto:
      type: object
      title: FeatureDto
      additionalProperties: false
      properties:
        id:
          type: integer
          format: int64
        label:
          type: string
        icon:
          type: string
        routerLink:
          type: string
        hasChildren:
          type: boolean
        parent:
          type: integer
          format: int64
        showInMenu:
          type: boolean
        orderValue:
          type: integer
    GroupMenuDto:
      type: object
      title: GroupDto
      additionalProperties: false
      properties:
        id:
          type: integer
          format: int64
        label:
          type: string
        icon:
          type: string
        orderValue:
          type: integer
    GroupMenuFeatureDto:
      type: object
      title: GroupMenuFeatureDto
      additionalProperties: false
      properties:
        id:
          type: integer
          format: int64
        label:
          type: string
        icon:
          type: string
        orderValue:
          type: integer
        features:
          type: array
          items:
            $ref: '#/components/schemas/FeatureDto'
    FeaturePageResponse:
      type: object
      title: FeaturePageResponse
      additionalProperties: false
      properties:
        result:
          $ref: 'lib/common.yaml#/components/schemas/ApiResult'
        context:
          type: array
          items:
            $ref: '#/components/schemas/FeatureDto'
        last:
          type: boolean